language: en
pipeline:
- name: WhitespaceTokenizer
  intent_tokenization_flag: true
  intent_split_symbol: +
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
- name: DucklingHTTPExtractor
  url: http://0.0.0.0:8000
  locale: en_IND
  dimensions:
  - time
  - number
  - ordinal
  - duration
  timezone: Asia/Kolkata

policies:
- name: KerasPolicy
  epochs: 50
  featurizer:
  - name: MaxHistoryTrackerFeaturizer
    max_history: 5
    state_featurizer:
    - name: BinarySingleStateFeaturizer
- core_threshold: 0.3
  name: FallbackPolicy
  nlu_threshold: 0.6
- name: MemoizationPolicy
  max_history: 5
- name: FormPolicy
- name: MappingPolicy
